### ISSUE TITLE
Auto-Recruiter logic needs fixing

### ISSUE THREAD

**Issue by uaktags** [uaktags/DarkCurse-nextjs#13]
Personal Recruit Links are so that you can give to someone else and receive a citizen if they click it (up to a limit)
The auto-recruiter allows users to simulate clicking through others links, and recruiting them into their army (giving you a citizen).

This historically was great for the players as it gave them a chance to gain more citizens in a day by doing an action, but it also had a monetary value to it for DT by allowing more ads be seen. We don't need the ads for now, but we do need to tweak so that the "clicker" gets the citizens.

**Comment by KamAlvarezz** [comment]
325 was the normal recruiter (Recruiting into your own army)
25 extra were from the PRL (Personal Recruit Link) Other players or non players clicked the link 

Legend (paid) players, used to get the 350 at start of the day (0:00)

**Comment by uaktags** [comment]
Issue should be good to go now. Reopen if any new concerns arise.
