### ISSUE TITLE
Profficiency Points not happening

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#21]
I click on Str Con & Dex but nothing happens. It doesn't seem to try to load anything when I click. It just won't click.
![Untitled](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/35d4ba96-9c19-4d82-857a-778b844d6406)

**Comment by uaktags** [comment]
```
[
  {
    "type": "PRICES",
    "level": 0
  }
]
```

seems new users aren't getting the full bonus_points structure. Gotta fix the defaults and add code to check/correct as needed.

**Comment by uaktags** [comment]
prisma is correct:
bonus_points Json? @default("[{\"type\": \"OFFENSE\", \"level\":0,\"type\": \"DEFENSE\", \"level\":0,\"type\": \"INCOME\", \"level\":0,\"type\": \"INTEL\", \"level\":0,\"type\": \"PRICES\", \"level\":0 }]")
