### ISSUE TITLE
Armory Defence

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#22]
![khvvvvv](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/86fdb8d2-4c8d-496b-95de-f0f1aede5303)
Am not able to buy / equip tier 1 defence items in the Armory. It say's Invalid item type, usage, or level. I tried to equip 1 Padded Hood. The other Defence items do not equip either. The Offence Armory is working as normal.

**Comment by uaktags** [comment]
doesn't work
{userId: 4, items: [{type: "HELM", quantity: 1, usage: "DEFENSE", level: 1}]

works
{userId: 4, items: [{type: "HELM", quantity: 1, usage: "OFFENSE", level: 1}]

must be an issue with the WeaponTypes query. checking
