### ISSUE TITLE
attacking issue

### ISSUE THREAD

**Issue by wjrichardson84** [uaktags/DarkCurse-nextjs#29]
As you can see, player has a lot of money out and negative army.  Went to attack, they took no losses and killed 65 of my troops in 1 attack.

![Screenshot 2023-11-11 081026](https://github.com/uaktags/DarkCurse-nextjs/assets/150527682/5408131b-960c-4261-8751-b4fc38b3aa53)

**Comment by uaktags** [comment]
Should be fixed with #28 #27
