### ISSUE TITLE
Unlocked with Armory lvl 1 not unlocked

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#30]
![UwLA1](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/fae86c74-370b-4bb6-b631-444cc3ffa706)
The Armory appears locked up though I have fort lvl 2 both in the defense and offense Armory

**Comment by uaktags** [comment]
The Leather Armory/Chainmail Armory is correct. We previously incorrectly had it based on Fort Level, when in reality Armory items unlocked with Structure Upgrades to the Armory. That's currently being worked on and will be implemented shortly
