### ISSUE TITLE
Economy deposits

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#31]
![economy](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/d687f584-9fb9-45f3-8ea4-7bb7308500db)
There seems a discrepancy between how many deposits it say's I have in Economy upgrade to the bank.

**Comment by uaktags** [comment]
maxDeposits was incorrectly referencing HouseLevel and not EconomyLevel. Correcting this now
