### ISSUE TITLE
Lvl discrepancy

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#32]
![lvl](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/96d1b5c9-df29-4bf5-aa76-46aa2ddc28a9)
It say's lvl 6 on the attack page but lvl 5 on the advisor and overview.

**Comment by BronzeMantis** [comment]
Ah maybe I didn't refresh the page. Seems corrected now

**Comment by uaktags** [comment]
The sidebar stats are grabbed via the session and are rechecked on an interval.
The attack page is server-side rendered and will most likely show a discrepenency immediately following an action until your local session has updated. Not much of an error or anything that we can really do about it that won't have a detrimental impact on the server.
