### ISSUE TITLE
Small pillages %

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/DarkCurse-nextjs#42]
I'm only getting a 5-10% pillage on some players. Are they in protected mode for testing purposes.

**Comment by uaktags** [comment]
There is no concept of protected modes or anything else.
The gold pillage is currently set to the following algorithm:

By default 80% of a defender's gold is at risk in a battle (or 8% per turn).
We then apply a level scale where we 95% of that is at risk if there's a 5level difference. Readmore here for other levels: https://github.com/uaktags/DarkCurse-nextjs/blob/84ff4994238ab749651e84556f429b30a8d2e618/src/app/actions.tsx#L591-L613

After the attack we check the fort's HP, and if it's 0, we increase the pillaged gold formula by another 5%.

And then its simply this % * defender's gold * attack turns used in battle, and you get either this answer or all of their gold, whichever is less

So if a defender has 10,000 gold on hand, and he is 2 levels ahead, you use 5 attack turns, and after the battle they have 0 fortHP, then you'd expect to get:
(8% * 35% * 105%) * 10000 * 5 = 1,470 gold

If the user was 5levels different, and they had greater than 0 fortHP, and you used 10 attack turns:
(8% * 95%) * 10000 * 10 = 7,600 gold
